### ISSUE TITLE
Add a REPL console

### ISSUE THREAD

**Issue by Malacath-92** [spelunky-fyi/overlunky#119]
Something that can be interfaced with from the dll interface so it can be disabled when in user mode (for PL)
I guess it would need to be its own Lua VM but not sure how to achieve it exactly.

**Comment by Dregu** [comment]
I meant to add this but never got around to it... Tab completion, command history and variables to easily access selected entities (like $0 in browser dev tools) were some grand plans I had in mind.

**Comment by Malacath-92** [comment]
We might be able to use https://github.com/antirez/linenoise for completion and history. As for variables, if we run this in a Lua VM like scripts you can just assign variables so something like this should just work
```
> ent = spawn(ENT_TYPE.MOUNT_TURKEY, 0, 0, LAYER.PLAYER, 0, 0)
   2134675
> get_entity(ent):carry(player[1].uid)
```
Is there any issue with this I am not seeing?
