### ISSUE TITLE
Player 2 becoming player 1 in coop

### ISSUE THREAD

**Issue by Mr-Auto** [spelunky-fyi/overlunky#137]
Kind of problem with the global table of players
i think we ether need to make it so players are always in the same position in that table or expose some more stuff from state?

**Comment by Dregu** [comment]
I know it's confusing, it's a table of human controller Player-entities that exist, dead or alive. I don't really want to touch the table too much though, a lot of old stuff might break.

In MP there are also PlayerGhosts and these may or may not coexist with their Player corpses. Some scripts may want to use the corpses and others may want ghosts instead. This probably needs some new interface, get_player(SLOT), get_ghost(SLOT), get_the_thing_currently_controlled_by(SLOT) or something.

**Comment by Mr-Auto** [comment]
i wanted to do it but can't find ghost entity anywhere in state, like which ghost correlates with which player slot. I guess i can get all ghost entities and check in there inventory which slot they belong

**Comment by Dregu** [comment]
I finally added these functions in #193
