### ISSUE TITLE
Game crashing and creating dump file on inject

### ISSUE THREAD

**Issue by NinetyKek** [spelunky-fyi/overlunky#143]
I and another user on reddit are having issues with overlunky crashing the game, both of us are first time users of overlunky. Ive tried WHIP and turning off antivirus, not sure what to do about this.

**Comment by Malacath-92** [comment]
Can you try some older versions so we can figure out when it broke?
Also please give us some information about your system, OS, CPU, RAM etc.

**Comment by Amperthorpe** [comment]
I'm having the same issue, on all Overlunky versions compatible with the latest Spelunky 2 version. The CMD windows shows this https://i.imgur.com/pCZoWIA.png 
Then it instantly closes and the game crashes with a dump.
I just copied my Spelunky 2 folder somewhere else, moved the steam_api64.dll file from the Mr. Goldbergs Steam Emulator as the instructions say. The copied install seems to work without launching Overlunky.

I'm on Win 10, i7 7700L, 16 GB RAM, RTX 2060.

**Comment by Amperthorpe** [comment]
So...it just works fine now after changing nothing? No idea.

**Comment by Mikimaul** [comment]
i have that problem too also on all and nothing helps.

I'm on Windows 10, i7 7700HQ, 16 GB RAM, GTX 1060

**Comment by Nallebeorn** [comment]
I had the same issue after upgrading both my copy of the Spelunky 2 install and Overlunky (which I installed and last used way back in November). Downgrading to 0.5.3 fixed the crash, but then I upgraded back to 0.5.5 and somehow it still works fine now (I first tried upgrading to WHIP, and did not make a difference). Very weird.

**Comment by Hayatory** [comment]
> I had the same issue after upgrading both my copy of the Spelunky 2 install and Overlunky (which I installed and last used way back in November). Downgrading to 0.5.3 fixed the crash, but then I upgraded back to 0.5.5 and somehow it still works fine now (I first tried upgrading to WHIP, and did not make a difference). Very weird.

Same happened to me, constant crash on launch ( 97cf2ba through modlunky 2), downgraded to 0.5.3 , launched, worked, upgraded to 97cf2ba (through modlunky 2), launched,  worked... interesting.

**Comment by gmjosack** [comment]
Thanks for all the notes. I think we have a good lead on what the cause might be thanks to these reports. Will update soon:tm:
