### ISSUE TITLE
Hiccuping with drawing functions

### ISSUE THREAD

**Issue by Mr-Auto** [spelunky-fyi/overlunky#147]
Some people (including me) experience problems when lot of drawing function are involved, lag spike every 2s or so (exp. entity info example from overlunky), i noticed after the vanilla one were added that they also have the same problem.

It's a lag every couple seconds. Does not seam to be issue with processing power (i run i7 4790K) which should have more then enough to do stuff, someone on the discord who also mentioned this problem had even better CPU.

Maybe it has something to do with how often the drawing callbacks are executed? But it does not seam to be problem with empty callback

**Comment by Dregu** [comment]
Just cleaning up issues here. This hiccupping still seems to occur when doing e.g. get_entity() for 2000 entities every guiframe, but using cached position data to draw those same entities seems absolutely fine. So just don't do too many things in a guiframe I guess.
