### ISSUE TITLE
Stun timer troubles

### ISSUE THREAD

**Issue by Dregu** [spelunky-fyi/overlunky#171]
Getting stunned while mounted results in random/too long stun times. I suspect some new damage hooks, like last time, cause this ain't happening in 0.5.9. Reproduced in 1236e5a.

The repro that happened in randomizer is: setting arrowtrap projectile to light arrow, getting a bunch of health so it doesn't kill you and riding a mount to the trap. Mount absorbs some of the damage and you get stunned for thousands of frames instead of something reasonable.

**Comment by Dregu** [comment]
Yeah upon closer inspection all stun times are busted again, with players and enemies getting anything from no stun to minutes of stun from any hit.

**Comment by zappatic** [comment]
Yeah, that's my fault indeed. Now that the actual values are exposed via the set_on_damage function, they have to be correct. 32-bit was too wide as the values were way too big in the callback. I put them on 8-bit, but that's too narrow it seems (even though I tested it quite a bit) as there's garbage coming through, giving high timers. I'll change it to 16 bit.
