### ISSUE TITLE
Disable game keys option doesn't give input back to game in exclusive fullscreen mode

### ISSUE THREAD

**Issue by Dregu** [spelunky-fyi/overlunky#18]
Borderless windowed or windowed mode should work fine though. Disabling the option and alt+tabbing should give input back to the game.

**Comment by lilspelunker** [comment]
Still not fixed, we need a fix!

**Comment by Dregu** [comment]
But.., the fix is in my last comment. I don't really care about this issue at all actually, it's just here to tell you about the fix (don't use fullscreen).

**Comment by lilspelunker** [comment]
It lags when I use borderless windowed, even with lowest graphics. I can run max graphics smooth on fullscreen.

**Comment by Dregu** [comment]
I added an alternative mode for this in 0.4.1 that should work in fullscreen
