### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Starthium** [spelunky-fyi/overlunky#181]
Spelunky 2 crashes whenever I start up Overlunky.
I've tried version 0.6.0, 0.5.9, and the WHIP build.
What do I do to fix this?

**Comment by GreenMario101** [comment]
I have the same issue the game recently updated on steam and I haven't been able to use overlunky since.

**Comment by Malacath-92** [comment]
The game got an update that broke the tools. I thought Overlunky had a popup to state this. But let's keep this open for future people wanting to complain about this.

The solution is to not use Overlunky, be patient and start using it again when the next stable release comes out.

**Comment by Starthium** [comment]
I got the new WHIP build, and it's still not working. It keeps on crashing.

**Comment by Dregu** [comment]
Wow, almost sounds like the exact opposite of what you were told to do so I wonder why it doesn't work.

**Comment by Starthium** [comment]
No, I meant the one that was released 2 days ago.
The two messages before my message were before the new WHIP build.

**Comment by Dregu** [comment]
Yes you immediately got the automated pre-release build that only has some random tile code fixes, as stated by the release notes. Just wait PATIENTLY for the STABLE release, which comes with a version number, an announcement and updates to the README, which still clearly states everything is for version 1.25.0b.

The update is being drafted in #179 if you want to follow the progress.
