### ISSUE TITLE
Rotate vanilla rendering 

### ISSUE THREAD

**Issue by jaythebusinessgoose** [spelunky-fyi/overlunky#183]
Would love to be able to rotate images/text via the vanilla rendering API, especially images. In the vanilla game, this is done with the sticker in the in-game menus, and with the dangly on the spears in the main menu.

**Comment by Mr-Auto** [comment]
Textures done in #177 ,whenever that's gets merged 
For text i don't think there is a way, unless you can point an in game example

**Comment by jaythebusinessgoose** [comment]
The text in the journal gets rotated in the weird three dimensional way during the page flip animation. 

I can't think of a spot where text is given a normal 2D rotation.

**Comment by Dregu** [comment]
I think text was completed in #282
