### ISSUE TITLE
Pause game

### ISSUE THREAD

**Issue by jaythebusinessgoose** [spelunky-fyi/overlunky#184]
I'd like to be able to skmulate what pausing the game does without having the pause menu open. Namely, what doesn't work about setting state.pause is:

- The music becomes glitchy instead of becoming muffled.
- The time_total timer pauses.
- Inputs can no longer be read (by get_io or by other means).

Having the blurry overlay would be a nice bonus; as long as it's possible to render vanilla rendering huds over it.

**Comment by Mr-Auto** [comment]
that's just `state.pause = 2` 
or something wrong with that as well?

**Comment by Mr-Auto** [comment]
I'm actually using this in the "SUPER HOT LUNKY" mod and i never heard anyone complaining about music problems

**Comment by jaythebusinessgoose** [comment]
3 has the same issue. I don't have OL open, but this issue happens whether I disable pausing in code via the state flags or if I don't.

**Comment by jaythebusinessgoose** [comment]
Ok, setting it the way you do in that script doesn't have the music issue, but does still have to following issues:

GAMEFRAME callbacks aren't called, I think I could resolve that by putting some of my callbacks as HUD callbacks instead. 

The state.time_total pauses. This is happening in super hot as well. Is there any other way to get a running timer or just some global "current time"?

**Comment by jaythebusinessgoose** [comment]
[Menus.zip](https://github.com/spelunky-fyi/overlunky/files/7927169/Menus.zip)

This is what I'm trying to do.

**Comment by Mr-Auto** [comment]
"GAMEFRAME" you mean `ON.GAMEFRAME` ? well, that is obvious as the game is paused, the same with the total timer, if you want to change that you need to do it manually, you can use `set_global_interval` to have something running all the time. `state.time_total` is running even when the game is paused, `state.time_level` is paused, but you can increment it by yourself 

don't know what you mean by `HUD callbacks`

**Comment by jaythebusinessgoose** [comment]
`state.time_total` is supposed to run while paused but does not when we pause this way.

By HUD callbacks, I mean `ON.RENDER_POST_HUD`.

**Comment by Mr-Auto** [comment]
render stuff runs on display refresh rate, not frames, so i don't recommend using it for anything other than drawing as it may lag for people with 144Hz monitors etc.

i don't think there is a way to do what you want to do, whatever you're trying to do

**Comment by jaythebusinessgoose** [comment]
Ok, does it sound like something that can be looked into once the api is fixed for the patch?

If nothing else, at least a way to get some global system time that never pauses would be nice.

**Comment by Mr-Auto** [comment]
ok, i found something `state.pause = 16` will leave `state.time_startup` running, and `set_global_interval` still works

**Comment by jaythebusinessgoose** [comment]
That's perfect! I don't know how I missed that `state.time_startup` even exists. 

Now all I have to do is update the total_time from that value when paused, which shouldn't bee too difficult. 

The only thing I think is missing is the blurry background and muffling of the music. Those aren't the most important, but would be nice if they are easy to do.

**Comment by Dregu** [comment]
Documented state.pause and added enum PAUSE explaining all this
