### ISSUE TITLE
Render vanilla text at the world level. 

### ISSUE THREAD

**Issue by jaythebusinessgoose** [spelunky-fyi/overlunky#185]
I'd like to be able to draw vanilla text at the world level at any draw depth like we can with images, so that the player passes over them.

**Comment by Mr-Auto** [comment]
Is there any example in the game of this? 
even just drawing text in game coordinates

**Comment by jaythebusinessgoose** [comment]
Someone pointed out that the shop "buy item" dialog text would render at the world level if the draw depth was changed such that it would render at that draw depth and be occluded by in-game objects that intersect with it.

**Comment by jaythebusinessgoose** [comment]
Also, the button inputs on the tutorial signs render at the world level. I am not sure if those are text, but the way we render button inputs is as text so they may be.

**Comment by Mr-Auto** [comment]
The buttons are just fx_button entity

i will check the "Buy %s" text

**Comment by Mr-Auto** [comment]
```lua
set_callback(function(render_ctx, draw_depth)
    if #players < 1 then return end
    if draw_depth == players[1].type.draw_depth - 1 then
        x, y, l = get_render_position(players[1].uid)
        y = y + 1.15
        rect = AABB:new(x-0.5, y+0.5, x + 0.5, y - 0.5)
        render_ctx:draw_world_texture(TEXTURE.DATA_TEXTURES_FLOOR_SURFACE_0, 1, 1, rect, Color:white(), angle, 1, 1)
        s_x, s_y = screen_position(x, y+1.0)
        render_ctx:draw_text("Text scale", s_x, s_y, 0.001, 0.001, Color:white(), 1, 1)

    end
end, ON.RENDER_PRE_DRAW_DEPTH)
```
