### ISSUE TITLE
Clovers seem to not take effect

### ISSUE THREAD

**Issue by lyraderg** [spelunky-fyi/overlunky#19]
When I played with Overlunky on (0.3.5) I found that whenever I picked up a clover, they immediately had the wilting animation. The ghost came at the normal time as if the clover were not in effect. I had been playing with Overlunky in order to practice with the telepack instead of having to rely on RNG to spawn it, but something like the clover not working is enough of a bug that I am not using it for now. If there's any more information I should provide, let me know.

**Comment by Dregu** [comment]
This should be fixed in 0.3.6 along with other flags getting messed up by the "Disable pause menu" option.
