### ISSUE TITLE
Stop music relooping on death

### ISSUE THREAD

**Issue by jaythebusinessgoose** [spelunky-fyi/overlunky#194]
Would be nice to have a way to keep the music going after a death when restarting the run.

**Comment by Mr-Auto** [comment]
I looked into it, the music, can be done but what about being in Volcana, die, and then restart to Dweling?
they have different musics so you either restart to Dweling music anyway or keep playing Volcana music (which would be very confusing) 

If you want the music just during the death screen, you can do it right now, with the exposed backgroundmusic in gamemanager

**Comment by jaythebusinessgoose** [comment]
wait, this was fixed? how do we stop the music from reloopong?

**Comment by Dregu** [comment]
I dunno, discussion seemed pretty stale.

**Comment by Dregu** [comment]
All the music tracks of different screens should be accessible but Auto had a good point about the theme changes etc.

**Comment by jaythebusinessgoose** [comment]
Theme changes are separate from deaths though, I don't think anyone would care if the music starts from the beginning when changing themes. The desire is for restarting after a death to act the same as restarting without a death. 

The music restarts on death regardless of any screen changes too.

**Comment by Dregu** [comment]
```lua
P:set_pre_kill(function(ent)
  load_death_screen()
  return true
end)

**Comment by Mr-Auto** [comment]
I did it once but it required a lot of changes as the sound is killed and cleared in the gamemanager in multiple places in code. 
It just sounds like a lot of bugs to make it work how you want it to.

The code that Dregu posted is probably the best you can get, maybe an vtable hook to the update virtual of the SoundMeta could help with the sound resetting to dwelling in other themes
