### ISSUE TITLE
Lua scripts wont load

### ISSUE THREAD

**Issue by Starthium** [spelunky-fyi/overlunky#205]
I've been having trouble with loading the lua scripts, the base ones are already in the scripts file, but whenever I look in the scripts tab in-game, none appear.
Is this a problem that everyone else is having, or is it just me?
I've tried version 6.1 and the WHIP build, but both wont work.

**Comment by Mr-Auto** [comment]
Overlunky folder has to be in the game directory for the scripts to work

**Comment by Starthium** [comment]
What is the game directory? Is it a file in the local files?
