### ISSUE TITLE
Game crashes during spinning animation after completing Cosmic Ocean.

### ISSUE THREAD

**Issue by denialromeo** [spelunky-fyi/overlunky#208]
Love the app. Thanks so much for it.

I'm on Windows 11, running on Steam conventionally. I've been able to warp to and beat Hundun and have my progress saved without any issues.

But when I warp to 7-98 and make it through the door, I spin for a bit and then the game crashes.

I suspect this is unavoidable behavior (it's possible that warping to 7-98 directly doesn't let the game know what it needs to know for the ending constellation), but just creating this issue in case it's a bug that can be resolved.

**Comment by Mr-Auto** [comment]
Just tested and works fine for me on the latest whip build, even when warping directly from Main Menu

**Comment by Malacath-92** [comment]
I just got a Win 11 PC so I can see if that's specific to that, but I kinda doubt it.

**Comment by denialromeo** [comment]
Thanks!

Just tried again. Still an issue on my end.

Is there a debug mode I can enable so I can copy and paste more helpful output?

Right now, Overlunky just looks like this for me -

```
C:\Users\hi\Desktop\code>overlunky
[info] Overlunky version: 0.6.1
[info] Searching for Spel2.exe process... Pro tip: You have to launch it yourself.
[info] Found Spel2.exe PID: 4648
[debug] Allocated memory: 0x27201ca0000
[debug] Injecting DLL into process... C:\Program Files (x86)\Steam\steamapps\common\Spelunky 2\Overlunky\injected.dll
[debug] Calling: 0x7ffef4b8f500
[debug] Calling: 0x7ffe451daae0
```

**Comment by gmjosack** [comment]
Looks like you're possibly using 0.6.1 which is from Feb. Have you tried the WHIP build? https://github.com/spelunky-fyi/overlunky/releases/tag/whip

**Comment by denialromeo** [comment]
Thanks!

Just tried. Crashed again in the same way!

```
C:\Users\hi\Desktop>overlunky
[info] Overlunky version: e653f1e
[info] Searching for Spel2.exe process... Pro tip: You have to launch it yourself.
[info] Found Spel2.exe PID: 33452
[debug] Allocated memory: 0x26500000000
[debug] Injecting DLL into process... C:\Program Files (x86)\Steam\steamapps\common\Spelunky 2\Overlunky\injected.dll
[debug] Calling: 0x7ffef4b8f500
[debug] Calling: 0x7ffe4509f7f0
```

**Comment by Malacath-92** [comment]
Interesting, I can reproduce this on my Win11 machine. I'll try to figure out what's up, but not sure if I will get any fix done today.

**Comment by Dregu** [comment]
I have no idea if we've tried to fix this or not, but I'm trying to clean up in here so what's up? The only consistent constellation crash I know of was loading the ending with level_count == 0, but going through the door should increment it anyway.
