### ISSUE TITLE
How to load scripts?

### ISSUE THREAD

**Issue by Starthium** [spelunky-fyi/overlunky#222]
For atleast 3 months now, Overlunky hasn't been loading scripts, even though it worked fine before.
I tried moving the Overlunky folder into my steamapps folder, and they still wont work.
How do I fix this?

**Comment by Dregu** [comment]
Scripts are probably not in the right place. Put them to the directory mentioned in https://github.com/spelunky-fyi/overlunky#scripts or edit the path in overlunky.ini if you want to put them somewhere else. If you just run overlunky from a random place, scripts won't load.
