### ISSUE TITLE
Cannot destroy entity ID 0 with mouse_destroy input

### ISSUE THREAD

**Issue by Cosine256** [spelunky-fyi/overlunky#228]
The entity with ID 0 cannot be destroyed by the `mouse_destroy` or `mouse_destroy_unsafe` inputs. Nothing happens to it when pressing these inputs while hovering over it. Entity 0 is typically a floor or door entity somewhere near the top-left corner of the level. Other entities in the same area can be destroyed normally with these inputs. Other methods of destroying entity 0, such as the Entity UI, work correctly.

I have these inputs bound to Mouse5 and Shift+Mouse5 respectively, which I believe are the defaults.

**Comment by Dregu** [comment]
Are you on the super old stable version? This should be fixed for a while in WHIP. New stable is overdue though...

**Comment by Cosine256** [comment]
You're right, I downloaded the latest version of Overlunky via Modlunky and this issue is fixed there. I didn't realize the stable build I was using was that far behind. I'll go ahead and close this.
