### ISSUE TITLE
Cannot find library in the target process: KERNEL32.DLL (case sensitivity)

### ISSUE THREAD

**Issue by VDZx** [spelunky-fyi/overlunky#23]
An earlier version of Overlunky (I think it was 0.2.1 or something) worked fine for me, but 0.4.0 and 0.4.1 fail to work out of the box. It attemps to inject, but gets an error and quits:

[info] Overlunky version: 0.4.1
[info] Searching for Spel2.exe process...
[info] Found Spel2.exe PID: 19156
[info] Game was just started, waiting a few seconds for it to load before injecting...
[debug] Allocated memory: 0x5ea0000
[debug] Injecting DLL into process... D:\onzin\Overlunky\injected.dll
[error] Cannot find library in the target process: KERNEL32.DLL

I poked around the source code and noticed find_base seems to use a case-sensitive string search (via std::string::find), which I think comes from inject_dll -> find_function. Hex-editing the "KERNEL32.DLL" string into the lowercase "kernel32.dll" makes Overlunky work on my PC, so the case-sensitive search is probably the cause. (I can just replace the string in a hex editor whenever I update as a workaround, but this is likely to affect others as well, possibly all Win7 users.)

**Comment by gmjosack** [comment]
New release just landed with a potential fix for this if you wanna test it out.

**Comment by VDZx** [comment]
Yup, it works out of the box now.
