### ISSUE TITLE
massive visual glitch

### ISSUE THREAD

**Issue by Boggy23** [spelunky-fyi/overlunky#240]
recently, i got overlunky again, but every time i try to run the game with it, i get these massive visual glitches. is there any way i could fix this?
![2022-06-20 (1)](https://user-images.githubusercontent.com/90582987/174679271-45519715-9fd2-4c11-9673-22e9bd410a14.png)

**Comment by Mr-Auto** [comment]
Are you on the latest version? 
try Whip build <https://github.com/spelunky-fyi/overlunky/releases>

**Comment by Boggy23** [comment]
i am, ill try wip rn

**Comment by Dregu** [comment]
I guess it worked 🤷🏻‍♂️
