### ISSUE TITLE
PRNG:random_chance not working as expected

### ISSUE THREAD

**Issue by Cosine256** [spelunky-fyi/overlunky#242]
The function `PRNG:random_chance(inverse_chance, type)` is documented as returning `true` with a chance of `1/inverse_chance`, but I'm observing a chance of `1/(inverse_chance+1)`.

To demonstrate this, run the following code in the Overlunky console:
```
local trials = 100000
for inverse_chance = 0, 5 do
    local hits = 0
    for i = 1, trials do
        if prng:random_chance(inverse_chance, PRNG_CLASS.PROCEDURAL_SPAWNS) then
            hits = hits + 1
        end
    end
    print("random_chance("..inverse_chance.."): "..hits.."/"..trials.." ("..(hits / trials)..")")
end
```

Here is a sample output from running that code in Overlunky build b9dbe53:
```
random_chance(0): 100000/100000 (1.0)
random_chance(1): 50240/100000 (0.5024)
random_chance(2): 33525/100000 (0.33525)
random_chance(3): 25097/100000 (0.25097)
random_chance(4): 19893/100000 (0.19893)
random_chance(5): 16460/100000 (0.1646)
```

**Comment by Malacath-92** [comment]
I think saying "on purpose" is stretching things  😅  Probably did a doozy when thinking about `prng:random_chance(0)` which should not give us 1.0 but 0.0, right? So that should probably be fixed in code.

**Comment by Dregu** [comment]
Fixed in WHIP
