### ISSUE TITLE
Can't inject on Proton (7.0-4) any more

### ISSUE THREAD

**Issue by Dregu** [spelunky-fyi/overlunky#256]
Worked fine when Proton 7 was released, worked fine even with Proton 6.3. Now it doesn't work on any Proton version when running from Steam with launch options `--launch_game ..`, and this feature was specifically added for Proton support and well tested to work back then... I don't know what happened.

Wine-7.14 + DXVK + GoldBerg Emulator still works fine.

```
[info] Overlunky launcher version: b442ddd
[info] AutoUpdate: Disabled, delete overlunky.version to enable again.
[info] Game path was passed on cmd line, launching game directly...
Setting breakpad minidump AppID = 418530
SteamInternal_SetMinidumpSteamID:  Caching Steam ID: * [API loaded no]
[info] Waiting a few seconds before injecting...
[debug] Allocated memory: 0x1ef0000
[debug] Injecting DLL into process... Z:\home\dregu\.local\share\Steam\steamapps\common\Spelunky 2\Overlunky\injected.dll
[debug] Calling: 0x7b60daf4
[error] Cannot find the address of the library in current process: Z:\home\dregu\.local\share\Steam\steamapps\common\Spelunky 2\Overlunky\injected.dll
```

**Comment by seancmonahan** [comment]
Prepending `PROTON_LOG=1` to the Launch Options for both Overlunky and Spelunky 2, the log for Overlunky shows that `4433.564:012c:0130:err:module:import_dll Library MSVCP140_CODECVT_IDS.dll (which is needed by L"Z:\\home\\sean\\.local\\share\\Steam\\steamapps\\common\\Spelunky 2\\Overlunky\\injected.dll") not found`. (This is with Overlunky in a subfolder of Spelunky 2, like you have.)

Moving the contents of Overlunky/ up directly into the Spelunky 2 directory and changing the Steam shortcut and launch options to `PROTON_LOG=1 %command% --launch_game .`, Overlunky.exe now launches Spelunky 2 and seems to inject the dll. A small text displaying `Overlunky 0072402` shows at the bottom of the game window, but I don't see the overlay, and none of the shortcut keys (function keys, etc.) from the readme seem to do anything. I don't have an overlunky.ini file though, and I'm not sure whether Overlunky has defaults.

**Comment by Dregu** [comment]
The injection method was changed in #283 when using the `--launch_game` parameter, mainly to fix a lot of linux and proton problems. Also symlinking the missing DLLs to the Overlunky directory may help. I fixed my own issues with these, but Linux is a jungle.
