### ISSUE TITLE
Overlunky WHIP and 1.27

### ISSUE THREAD

**Issue by serial417** [spelunky-fyi/overlunky#258]
I have Tried running different types overlunky but it keeps saying something not found
and I have tried reinstalling spelunky 2 and overlunky but it just will not work anyone know how to fix this?

**Comment by gmjosack** [comment]
A new patch for spelunky 2 just came out last night (1.26). It'll take some time before it works again

**Comment by serial417** [comment]
Ok Thank You!

**Comment by gmjosack** [comment]
I'm going to leave this open for now so others see it

**Comment by Dregu** [comment]
The latest WHIP build now works (barely) with 1.26, but a lot of random functionality is simply disabled. Running scripts is probably pretty folly. Basic UI functions are probably fine. I had to delete overlunky.ini to get it to start. Progress is being made in #259, but this might be futile cause a new patch is probably coming in the following weeks.

**Comment by Dregu** [comment]
I think Mr.Auto fixed it. Let me know!
