### ISSUE TITLE
I cannot start overlunky without the game crashing

### ISSUE THREAD

**Issue by Beebopidop** [spelunky-fyi/overlunky#267]
Now I'm in no way a computer nerd, but I think I know what it means, I just need it to be fixed
I start up Overlunky and Spelunky 2, and i am greeted to this:

Overlunky 0.6.3
--------------

Error

Failed finding ' ghost_spawn_time_cursed_player2 ' ('30 b8') in
Spel2.exe

Running Spelunky 2: unknown!
Supported Spelunky 2 1.25.0b

Overlunky 0.6.3
---------------

**Comment by Malacath-92** [comment]
Use the WHIP build instead

**Comment by Beebopidop** [comment]
funny how things are solved with whips
