### ISSUE TITLE
set_post_entity_spawn executed with wrong LuaBackend

### ISSUE THREAD

**Issue by Cosine256** [spelunky-fyi/overlunky#278]
The `set_post_entity_spawn` callback executes with the LuaBackend of the script that spawned the entity, rather than the script that registered the callback. This likely causes many issues, but these are three I noticed during my testing. All testing was done with Overlunky build 22b1887.

* Console messages are attributed to the wrong script.
* Additional callbacks created within `set_post_entity_spawn` are registered to the wrong script.
* The `Entity.user_data` reference is from the wrong script.

Below are two scripts that can be dropped into the scripts directory to reproduce the problem:

```
meta.name = "Entity Spawn Listener"

set_post_entity_spawn(function(ent)
    ent.user_data = "Entity Spawn Listener was here"
    prinspect("Entity Spawn Listener: set_post_entity_spawn user_data", ent.user_data, get_frame())

    local ent_id = ent.uid
    set_timeout(function()
        prinspect("Entity Spawn Listener: set_timeout user_data", get_entity(ent_id).user_data, get_frame())
    end, 30)
end, SPAWN_TYPE.ANY, MASK.ITEM, ENT_TYPE.ITEM_ROCK)
```

```
meta.name = "Entity Spawner"

register_option_button("spawn_entity", "Spawn entity", "", function()
    local x, y, layer = get_position(players[1].uid)
    local ent = get_entity(spawn_entity(ENT_TYPE.ITEM_ROCK, x, y, layer, 0, 0))
    prinspect("Entity Spawner: spawn_entity user_data", ent.user_data, get_frame())
    ent.user_data = "Entity Spawner was here"
    
    local ent_id = ent.uid
    set_timeout(function()
        prinspect("Entity Spawner: set_timeout user_data", get_entity(ent_id).user_data, get_frame())
    end, 30)
end)
```

Observed output after pressing the "Spawn entity" button once:

```
[Entity Spawner] "Entity Spawn Listener: set_post_entity_spawn user_data", "Entity Spawn Listener was here", 6776
[Entity Spawner] "Entity Spawner: spawn_entity user_data", "Entity Spawn Listener was here", 6776
[Entity Spawner] "Entity Spawn Listener: set_timeout user_data", "Entity Spawner was here", 6806
[Entity Spawner] "Entity Spawner: set_timeout user_data", "Entity Spawner was here", 6806
```

Issues with this output: 
* All printed messages are attributed to Entity Spawner.
* Entity Spawner sees the `user_data` written by Entity Spawn Listener before writing its own `user_data`.
* Both timeouts see the new `user_data` written by Entity Spawner.

I did not test whether this occurs with `set_pre_entity_spawn`, nor any other callbacks.

**Comment by Malacath-92** [comment]
Should be fixed in next WHIP/Nightly builds via [e3c9bb0](https://github.com/spelunky-fyi/overlunky/commit/e3c9bb0eabb5498fceb7a4c2a384d2beaa5c4518)
