### ISSUE TITLE
Entity clear_virtual does not work as a method

### ISSUE THREAD

**Issue by Cosine256** [spelunky-fyi/overlunky#291]
The `Entity.clear_virtual` Lua function is documented as an Entity method with the signature `clear_virtual(CallbackId callback_id)`, but using it in this way causes an error.

Run this in the OL console while in a level with a player (you don't actually need callback ID 0 to exist):
`P:clear_virtual(0)`

Error output (abridged):
`sol: runtime error: stack index 1, expected number, received sol.void) [T = Player *]: not a numeric type that fits exactly an integer`

The function expects an integer in place of the implicit `self` parameter, not an Entity, and so it cannot be used as a method.

This call is able to clear the callback (note the `.`, not `:`):
`P.clear_virtual(P.uid, 0)`

**Comment by Dregu** [comment]
Yep the implementation is clearly wrong, but the fix was very easy too. Only the deprecated global function should use uids. I guess even Mal got too cross-eyed from all the templates, cause I certainly did while reviewing.

**Comment by Dregu** [comment]
Pushed fix, hope it was as simple as it seemed.

**Comment by Malacath-92** [comment]
Lgtm, I did indeed miss that, and being the god programmer I apparently think I am I didn't test it either  🤦
