### ISSUE TITLE
dmcrate spawning crashes the game

### ISSUE THREAD

**Issue by Alexcm1015** [spelunky-fyi/overlunky#31]
Not sure if this issue happens for everyone but when you try to spawn a deathmatch crate or the indicator that spawns one it crashes the game, normally this wouldn't be an issue but they sometimes replace enemies in the randomizer and that immediately crashes it as well.

**Comment by Dregu** [comment]
No they don't.

**Comment by Dregu** [comment]
Or maybe if you're using an old version after the 1.20.3a update moved all the entity ids.
