### ISSUE TITLE
Add a directory that mods can safely read/write any number of files to.

### ISSUE THREAD

**Issue by jaythebusinessgoose** [spelunky-fyi/overlunky#336]
For some mods, it's nice/necessary to read and write more/larger files. This can be done in unsafe mode, but it would be great to do in normal safe play.

I think a generated folder Mods/Data/<Mod Name> for a mod in Mods/Packs/<Mod Name> would be a good safe spot for a mod's files and internal directories.

**Comment by Dregu** [comment]
Sounds reasonable and it's probably pretty straightforward to sandbox `io.open` to one folder. I suppose it would also be useful to copy files that shipped with the mod to this persistent data folder.
