### ISSUE TITLE
Spacebar menu input being blocked

### ISSUE THREAD

**Issue by Cosine256** [spelunky-fyi/overlunky#357]
The latest OL build (f44e576) is preventing me from interacting with S2 menus using spacebar. Other buttons (escape, enter, arrow keys) work fine, and spacebar works fine as a player input.

https://github.com/spelunky-fyi/overlunky/blob/f44e576dad16d148c8aface07b55821ca13dc334/src/injected/ui.cpp#L9308-L9312
I'm pretty sure the code above is what's causing it, but I don't really understand what that whole pause script is meant to be doing, since I'm having this issue while not even paused. I eventually figured out key 33 is Z and 40 is spacebar, but are these keys in an enum somewhere?

**Comment by Dregu** [comment]
Accepting space as menu input during frame advance really screwed with frame advance using the same key by default, but there reaaally should've been a check if space is actually the frame advance key...

**Comment by Dregu** [comment]
I pushed a fix. Also no, there's no enum yet, cause it's in some random order I didn't want to figure out yet.
