### ISSUE TITLE
State memory fade variables are named incorrectly

### ISSUE THREAD

**Issue by Cosine256** [spelunky-fyi/overlunky#362]
I think the state memory `fadeout` and `fadein` variables are named and documented incorrectly. It seems like they're actually a numerator and denominator used to compute `fadevalue`.

I believe this is how they are used:
- Fade-out of current screen (`loading == 1`): `fadevalue = 1.0 - (fadeout / fadein)`
- Fade-in to new screen (`loading == 3`): `fadevalue = fadeout / fadein`

In both cases, `fadeout` and `fadein` are set to some constant when the fade begins, and then `fadeout` counts down to 0, after which either `loading_black_screen_timer` gets decremented or loading progresses to the next step. If I do something like set `fadeout` and `fadein` to 255, then I can get a really long fade.

**Comment by Dregu** [comment]
Yeah these variables are probably literally one of the first 10 things in the API, when it was just a cheat engine structure, and nobody ever questioned it. Doesn't help that it sort of works out like it's documented with some confirmation bias.
