### ISSUE TITLE
No entities in list

### ISSUE THREAD

**Issue by BigLionbruh** [spelunky-fyi/overlunky#4]
So I open the game and there is no entities on the list and I just need to find a couple items and spawn them, yes I have already tried running the injector at the camp. Is there any way this can be fixed?

**Comment by EdgedFenc** [comment]
Also cant find any entities in the list

**Comment by BigLionbruh** [comment]
I found the entity number for the crate so I just spawn 1,000 of them and see what I get (by the way its 401)

**Comment by iojon** [comment]
I guess this issue is fixed with #6.
