### ISSUE TITLE
no entity codes in .16.1

### ISSUE THREAD

**Issue by 100procentorangejuice** [spelunky-fyi/overlunky#5]
no item/entity codes show up in gui in version spelunky 1.16.1 and the enitites.txt file is empty

**Comment by sonofgreengenes** [comment]
Having the same issue in the same version, i dont see an entities.txt and it wont let me search in game. When i visit the github link in the readme, it's 404d

**Comment by Dregu** [comment]
We don't care about old game versions. Update your game or if you stole it tough luck.
