### ISSUE TITLE
module 'io' not found in lua script

### ISSUE THREAD

**Issue by Flexlolo** [spelunky-fyi/overlunky#55]
I tried to make a simple script to write a file.

```
meta.unsafe = true

io = require("io")
file = io.open("test.txt", "w")
```

This code doesn't work and says that the module was not found.

**Comment by Dregu** [comment]
Not really going to give any assistance making unsafe scripts, but a) you're not supposed to require the libraries, they're already loaded by unsafe mode, and b) you can't create unsafe scripts inside the OL editor incase you're doing that.

**Comment by Flexlolo** [comment]
>Not really going to give any assistance making unsafe scripts
why?


>you're not supposed to require the libraries, they're already loaded by unsafe mode

If I just try to use io.open it gives me ```attempt to index a nil value (global 'io')``` error.

**Comment by Dregu** [comment]
> why?

Because all the information you need is already in the readme/script-api and if you can't even comprehend the documentation, I don't think you should be running unsafe scripts.
