### ISSUE TITLE
set_timeout is not stoping when instant warp

### ISSUE THREAD

**Issue by Mr-Auto** [spelunky-fyi/overlunky#78]
Probably set_interval as well, i think it should as they are very much used 'per level'

**Comment by Trixelized** [comment]
`set_interval` and `set_timeout` also stop when pausing and entering the options menu

**Comment by Mr-Auto** [comment]
also suggestion: make it so if you return false (or whatever value chosen) in set_interval it will stop it

**Comment by Dregu** [comment]
Fixed and added.
