### ISSUE TITLE
I tried opening Overlunky with Wine on Linux but it crashes

### ISSUE THREAD

**Issue by KSXGitHub** [spelunky-fyi/overlunky#8]
A dialog box appears and said:

```
Assertion Failed!

Program: Spel2.exe
File: imgui/imgui_draw.cpp
Line: 1909

Expression: "(0) && "Could not load font file""

Press OK to exit the program or Cancel to start the Wine debugger
```

**Comment by iojon** [comment]
Have you tried installing Segoe UI (including Segoe UI Bold) font in wine? I haven't test it, but this might resolve the issue.

**Comment by KSXGitHub** [comment]
@iojon I have tried installing the fonts from both pacman repository and winetricks, the same issue persists.

**Comment by Dregu** [comment]
I just put all the segoe ui ttf tiles to ~/.fonts on Arch and it works fine here.

**Comment by iojon** [comment]
Ah I uploaded a fix for the situation when Font directory is not `C:\Windows\Fonts`, so I expect the issue will be resolved in the next release.
