### ISSUE TITLE
Not clear what values are expected out of entity.color

### ISSUE THREAD

**Issue by jeremypepper** [spelunky-fyi/overlunky#85]
These colors are between 0,1 and not 0, 255. We should document this.
Note: I'm adding this issue just to remind myself to document this. You can assign me the issue

**Comment by Mr-Auto** [comment]
Why not make it 0-255 in lua and convert in the back end?
I had one issue when i set the color to 144/255 and wanted later to check it but the float is not the exact value, i think in the OL ui is also rounded, isn't ?
