### ISSUE TITLE
ITEM_CLIMBABLE_ROPE (350) crashes the game

### ISSUE THREAD

**Issue by ppizarror** [spelunky-fyi/overlunky#9]
Spawning item 350 crashes the game.

Using the latest version of the mod. Spelunky v 1.19.8c

**Comment by Mr-Auto** [comment]
Rope can't be just spawned like that, we have special function in the API now to spawn it properly:
https://spelunky-fyi.github.io/overlunky/#spawn_unrolled_player_rope
