### ISSUE TITLE
Killing hired help crash

### ISSUE THREAD

**Issue by Mr-Auto** [spelunky-fyi/overlunky#91]
When spawning hired hand directly and then killing him, the game crash, similar thing when spawned from coffin and then you stole input from him and kill him.

Some ai related problem i guess?

**Comment by Mr-Auto** [comment]
more light on the case, when spawning with overlunky, hh is missing inventory and ai_func, but when you steal input from him, that only clears his ai_func, so missing that is probably what's causing the crash, maybe we could write some code so when no ai_func is set, prevent the game from accessing that memory

**Comment by estebanfer** [comment]
Will this be fixed soon?

**Comment by Mr-Auto** [comment]
so, spawn_companion fixes the spawn problem, for the steal_input 
```lua
set_on_kill(hired_hand, function(self, killer)
    return_input(self.uid)
end)```
plus other checks when warping to next level etc.
