### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by GhostDog98** [spelunky-fyi/overlunky#97]
Is linux support ever planned/going to be forked?

**Comment by gmjosack** [comment]
No one is currently planning on adding native linux support as Spelunky doesn't run on linux natively, though It should work with wine. Someone posted instructions of how they got it working here: https://github.com/spelunky-fyi/overlunky/issues/59#issuecomment-859977528

If there are things that could make support work better then we're happy to take a pull request, there's not need to fork the project just for linux support.

**Comment by Dregu** [comment]
I have no issues running in wine or steam proton and all the information needed to do so has been in the readme forever...

`wine Spel2.exe; wine Overlunky.exe` is basically all I have to do in a recent wine after installing dxvk and the steam emulator. I don't use OL on my Steam installation, but I have tested it just for you guys and the proton command works fine too.
